export const IamportPaymentGateInfo = [
    {
        id: 1,
        name: "card",
        pg: "uplus.tlgdacomxpay",
        MID: "tlgdacomxpay",
        pay_method: "card",
        iconPath: "/images/payment/cardPayIcon.svg",
        description: "카드결제",
    },
    {
        id: 2,
        name: "trans",
        pg: "uplus.tlgdacomxpay",
        MID: "tlgdacomxpay",
        pay_method: "trans",
        iconPath: "/images/payment/accountTransferIcon.svg",
        description: "실시간 계좌이체",
    },
    {
        id: 3,
        name: "tosspay",
        pg: "tosspay.tosstest",
        MID: "tosstest",
        pay_method: "card",
        iconPath: "/images/payment/tossPayIcon.png",
        description: "토스페이",
    },
    {
        id: 4,
        name: "kakaopay",
        pg: "kakaopay.TC0ONETIME",
        MID: "TC0ONETIME",
        pay_method: "card",
        iconPath: "/images/payment/kakaoPayIcon.svg",
        description: "카카오페이",
    },
];
