export const PATH = {
  MAIN: "/",
  ONBOARDING: "/onboarding",
  SETTING: "/setting",
  TERMS: "/setting/terms",
  SERVICE: "/setting/terms/service",
  PERSONAL: "/setting/terms/personal",
  NOTICE: "/setting/notice",
  NOTICE_DETAIL: (noticeId) => `/setting/notice/detail/noticeId=${noticeId}`,
  REFUND: "/setting/refund",
  ACCOUNT: "/setting/account",
  SINGIN: "/signin",
  AGREEMENT: "/agreement",
  MYCOURSE: "/mycourse",
  MYPAGE: "/mypage",
  NOTIFICATION: (memberId) => `/notification?memberId=${memberId}`,
  PRO_CENTER: "/pro", // FIXME : should be change
  CS_CENTER: "https://pf.kakao.com/_xhSxjExj/chat",
  SEARCH: (search) => `store?search=${search}`,
};
