export const PATH = {
    MAIN: "/",
    ONBOARDING: "/onboarding",
    AGREEMENT: "/agreement",
    AGREEMENT_PERSONAL: "/agreement/personal",
    SETTING: "/setting",
    TERMS: "/setting/terms",
    SERVICE: "/setting/terms/service",
    SETTING_PERSONAL: "/setting/terms/personal",
    REFUND: "/setting/refund",
    ACCOUNT: "/setting/account",
    NOTICE: "/setting/notice",
    NOTICE_DETAIL: noticeId => `/setting/notice/detail/noticeId=${noticeId}`,
    SINGIN: "/signin",
    MYCOURSE: "/mycourse",
    MYPAGE: "/mypage",
    NOTIFICATION: memberId => `/notification?memberId=${memberId}`,
    PRO_CENTER: "/pro", // FIXME : should be change
    CS_CENTER: "https://pf.kakao.com/_xhSxjExj/chat",
    SEARCH: search => `store?search=${search}`,
};
