export const LOCAL_STORAGE_KEYS = {
    IS_GUEST: "IS_GUEST",
    IS_SERVICE_AGREE: "IS_SERVICE_AGREE",
    IS_PERSONAL_AGREE: "IS_PERSONAL_AGREE",
    IS_PUSHALARM_AGREE: "IS_PUSHALARM_AGREE",
    IS_MARKETINGALARM_AGREE: "IS_MARKETINGALARM_AGREE",
    IS_TUTORIAL_DONE: "IS_TUTORIAL_DONE",

    // TODO : change prefix USER -> MEMBER
    USER_EMAIL: "USER_EMAIL",
    USER_IMAGE: "USER_IMAGE",
    USER_NAME: "USER_NAME",
    USER_ID: "USER_ID",

    ACCESS_TOKEN: "accessToken",
    REFRESH_TOKEN: "refresh",
};
