export const LOCAL_STORAGE_KEYS = {
    IS_GUEST: "IS_GUEST",
    IS_SERVICE_AGREE: "IS_SERVICE_AGREE",
    IS_PERSONAL_AGREE: "IS_PERSONAL_AGREE",
    IS_PUSHALARM_AGREE: "IS_PUSHALARM_AGREE",
    IS_MARKETINGALARM_AGREE: "IS_MARKETINGALARM_AGREE",
    ACCESS: "access",
    REFRESH: "refresh",
    USER_EMAIL: "email",
    USER_IMAGE: "image",
    USER_NAME: "user_name",
    USER_ID: "user_id",
    IS_TUTORIAL_DONE: "is_TutorialDone",
};
