export const IconDict = {
  새로운: "InformationTag_New",
  추천한: "InformationTag_Recommended",
  "조회수가 높은": "InformationTag_View",
  "도전이 많은": "InformationTag_Challenged",
  "완주율이 높은": "InformationTag_Completed",

  대학생: "InformationTag_College",
  직장인: "InformationTag_Office",
  남성: "InformationTag_Man",
  여성: "InformationTag_Woman",
  "10대": "InformationTag_Teens",
  "20대": "InformationTag_Twenties",
  "30대": "InformationTag_Thirties",
  "40대": "InformationTag_Forties",
  "50대": "InformationTag_Fifties",

  스포츠: "InformationTag_Sports",
  어학: "InformationTag_Langauge",
  투자: "InformationTag_Investment",
  요리: "InformationTag_Cooking",
  교양: "InformationTag_LiberalArts",
  컴퓨터: "InformationTag_Computers",
  음악: "InformationTag_Music",
  사진: "InformationTag_Camera",
  패션: "InformationTag_Clothes",
  공예: "InformationTag_Crafts",

  직무개발: "SummarizedTag_JobDevelopment",
  자기계발: "SummarizedTag_SelfDevelopment",
  재테크: "SummarizedTag_Finance",

  "1주": "SummarizedTag_1Week",
  "1.5주": "SummarizedTag_1Week",
  "2주": "SummarizedTag_2Week",
  "2.5주": "SummarizedTag_2Week",
  "3주": "SummarizedTag_3Week",
  "3.5주": "SummarizedTag_3Week",
  "4주": "SummarizedTag_4Week",
  "4.5주": "SummarizedTag_4Week",
  "5주": "SummarizedTag_5Week",
  "5.5주": "SummarizedTag_5Week",
  "6주": "SummarizedTag_6Week",
  "6.5주": "SummarizedTag_6Week",

  쉬움: "SummarizedTag_Easy",
  보통: "SummarizedTag_Normal",
  어려움: "SummarizedTag_Difficult",

  무료: "SummarizedTag_Free",
  유료: "SummarizedTag_Price",

  "1차시": "SummarizedTag_1Session",
  "2차시": "SummarizedTag_2Session",
  "3차시": "SummarizedTag_3Session",
  "4차시": "SummarizedTag_4Session",
};
